### ISSUE TITLE
[OBS] Change toggle-able actions to just toggle actions

### ISSUE THREAD

**Issue by rnayabed** [stream-pi/essential-actions#11]

**Comment by TOGLK** [comment]
This should not just be for OBS.

This feature should be implemented across the entire Stream-Pi application interface as a "Feature" for ANY "Action" that is usable.

**Comment by rnayabed** [comment]
Yes

**Comment by rnayabed** [comment]
> This should not just be for OBS.
> 
> This feature should be implemented across the entire Stream-Pi application interface as a "Feature" for ANY "Action" that is usable.

currently its just obs that makes sense to implement all this. Yeah in the future itll be implemented in all future actions if it makes sense to.
