### ISSUE TITLE
[Cross-Platform] [Feature Request] [OBS Action Plugin] Add action to trigger "Connect to OBS Websocket" (Original Post by Sranjb2)

### ISSUE THREAD

**Issue by TOGLK** [stream-pi/essential-actions#18]
What Platform is being Targeted?:
 All Supported Platforms

Is this a Bug-Fix, Feature Request, or, Other?:
 Feature Request

Describe the Issue:
 Currently there is a "Connect At Startup" button available within the settings, But if the user wishes to use a "Hotkey Action"
 to launch OBS then there should be a way to connect to OBS without entering the settings manually.
 (This is not targeted at SLOBS just yet, but this feature should support SLOBS in the future. SLOBS - StreamLab's OBS.)
 I believe this would be a great QOL (Quality Of Life) Update.
 
 
The original issue is here:
https://github.com/stream-pi/client/issues/47

**Comment by sranjb2** [comment]
thanks for reposting it!
