### ISSUE TITLE
OBS temporarily displays a *Random* scene during Scene Transitions

### ISSUE THREAD

**Issue by TOGLK** [stream-pi/essential-actions#20]
Target Platform:
  Cross-Platform

Is this a Bug-Fix, Feature Request, or, Other?:
  Bug-Fix

What Platforms (Operating Systems) Were Used?:
  (Host) Server - Stream-Pi Server for Windows (x86) Ver.1.0.0 EA2 - Windows 10 (x86-64)
  (Guest) Client - Stream-Pi Client for Android (ARM x64) Ver.1.0.0 EA2 - Android (ARM)
  
Describe the Issue:
  When using the OBS Action for Scene Transitions on occasions during the transition of one scene to another the screen 
  will temporarily display a *random* scene that changes every time you transition. This doesn't occur when you change the 
  scene using a mouse/cursor input.

What Solution do you suggest to Resolve the Issue?:
  Check how the OBS Web Socket Plugin accesses RAM & Cached Data, this may be an issue with the Stream-Pi OBS 
  Web Socket Plugin calling for All Scene's to be displayed before immediately transitioning to the Target Scene. This is just a 
  thought and not based on any evidence other than limited experience.

Who was the Issue initially reported by?:
  Cucciolo Di Informatico (Lorenzo Del Bello/Riccio Meticcio) - Italy
  
***Do you have concerns about the details of this GitHub Issue? If you do then please comment below, Or, Contact me directly via GitHub/Discord/Element.io***

**Contact Details:
   Discord - TOGLK
   Element.io (Matrix) - TOGLK
   GitHub - TOGLK**

**Comment by rnayabed** [comment]
> (Host) Server - Error! Platform Unknown!

??

**Comment by TOGLK** [comment]
> > (Host) Server - Error! Platform Unknown!
> 
> ??

The original reporter has not yet provided me with a known "(Host) Server Platform", So due to this lack of information I am unable to fill in those details.

A request has been made to the original reporter for those details and I will update this GitHub Issue accordingly once those details have been received.

**Comment by TOGLK** [comment]
> > (Host) Server - Error! Platform Unknown!
> 
> ??

The original post has been updated to reflect the new changes and information provided by the original reporter.

**Comment by rnayabed** [comment]
Does this happen with the newest build, websocket and OBS builds? I am closing this until someone can confirm this is still hapenning
