### ISSUE TITLE
[Cross-Platform] [Feature Request] [Macro Action] Ability to combine two or more actions into one Button

### ISSUE THREAD

**Issue by dartharnold** [stream-pi/essential-actions#61]
Target Platform:
Cross-Platform

Is this a Bug-Fix, Feature Request, or, Other?:
Feature Request

Describe the Issue:
The Requirement to use two button to send a CTRL-C and then a block of text.

What Solution do you suggest to Resolve the Issue?:
Create a button item that allows combination of other action into a macro type action.  Example: combine a Hotkey Action of CONTROL,C and a Text Block Action of "Hello All" to open chat area (Ctrl-C) and then send "Hello All".

**Comment by rnayabed** [comment]
This is already possible. `Combine Action` allows combining 2 or more actions into one.
