### ISSUE TITLE
Trigger website in background

### ISSUE THREAD

**Issue by eivindhusby** [stream-pi/essential-actions#68]
Triggering a "Website" command opens the webpage.
Would it be possible to let it send the command in the background, without opening the webpage?
Comparable to the "GET request in background" option on a Stream Deck.
I want to use Stream-Pi to control a web interface, and the current setup opens a webpage each time I send a command.

**Comment by rnayabed** [comment]
Thanks for letting know. This will be created asap

**Comment by rnayabed** [comment]
https://user-images.githubusercontent.com/25760501/158072243-af0895d1-d733-4895-b30d-03d4fe4a62ec.mp4

**Comment by rnayabed** [comment]
This has been included in the latest snapshot builds, and will be available in Version 2.0.0 by default.
