### ISSUE TITLE
Webhookaction Validate URL to be Secure

### ISSUE THREAD

**Issue by DannySF** [stream-pi/essential-actions#69]
The HttpsURLConnection used in the WebhookAction only allows HTTPS, meaning http fails without any notification towards the user.
I would suggest doing some validation on the URL input, or allow to use unsecure connections as well.

**Comment by rnayabed** [comment]
![image](https://user-images.githubusercontent.com/25760501/164049850-a50353a5-5935-42fd-836d-8b9adf3cf7fe.png)
2.0.0 Webhook addresses this issue. https://github.com/stream-pi/essential-actions/commit/d3eec71b61aac8ffed76d680dc28e5623fbbc8d9
2.0.0 Snapshot Build 119+ of Stream-Pi Server has this new action in it.
You may try it out, if there is any issue, then this issue will be re-opened or a new one will be created.
