### ISSUE TITLE
OBS URL

### ISSUE THREAD

**Issue by Raspipython** [stream-pi/essential-actions#71]
Hello, im new with the Raspbrry Pi and Github.
I downloaded the Stream-Pi stuff and it works really good but I cant find out how i connect OBS to my Stream-Pi(I dont know how I can find out hat the URL is. I hope anyone can help me so that I can use all features of the Stream-Pi.

**Comment by Raspipython** [comment]
OOps ist okay i forgot to install the plugin

**Comment by rnayabed** [comment]
![image](https://user-images.githubusercontent.com/25760501/173222046-c5656dd8-0e21-409d-aaa8-499d6bc58be1.png)

**Comment by rnayabed** [comment]
![image](https://user-images.githubusercontent.com/25760501/173222082-1f27aaa4-3df6-49e3-9209-8996e9cbfff1.png)

**Comment by rnayabed** [comment]
![walter-white-walter](https://user-images.githubusercontent.com/25760501/173222162-6d87bf13-1087-4024-b345-799ec16fbeb2.gif)
